package cli

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/justblue/mirage/internal/dialect/postgres"
	"github.com/justblue/mirage/internal/generator"
	"github.com/justblue/mirage/internal/validate"
)

func formatMigrationFile(mf *generator.MigrationFile) string {
	var b strings.Builder

	fmt.Fprintf(&b, "-- Migration: V%s_%s\n", mf.Version, mf.Description)
	fmt.Fprintf(&b, "-- Generated by mirage at %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "-- Checksum: %s\n", mf.Checksum)
	if mf.Message != "" {
		fmt.Fprintf(&b, "-- Message: %s\n", mf.Message)
	}

	if mf.HasDestructive {
		b.WriteString("--\n")
		b.WriteString("-- WARNING: destructive changes in this migration:\n")
		b.WriteString("--\n")
	}

	b.WriteString("\n-- +migrate Up\n\n")

	for _, s := range mf.UpStatements {
		b.WriteString(s + "\n\n")
	}

	if len(mf.AutocommitStatements) > 0 {
		b.WriteString("\n-- Autocommit statements (run outside transaction):\n\n")
		for _, s := range mf.AutocommitStatements {
			b.WriteString(s + "\n\n")
		}
	}

	b.WriteString("-- +migrate Down\n\n")

	for _, s := range mf.DownStatements {
		b.WriteString(s + "\n\n")
	}

	return b.String()
}

func nextSequentialVersion(dir string) string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "00001"
	}
	maxVer := 0
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".sql") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".sql")
		if !strings.HasPrefix(name, "V") {
			continue
		}
		parts := strings.SplitN(name[1:], "_", 2)
		if len(parts) != 2 {
			continue
		}
		var n int
		if _, err := fmt.Sscanf(parts[0], "%d", &n); err != nil {
			continue
		}
		if n > maxVer {
			maxVer = n
		}
	}
	return fmt.Sprintf("%05d", maxVer+1)
}

func getDialect() *postgres.Postgres {
	return postgres.New()
}

func countErrors(errs []validate.ValidationError) int {
	n := 0
	for _, e := range errs {
		if e.IsError() {
			n++
		}
	}
	return n
}
