package schema

import (
	"fmt"
	"reflect"
	"strings"
)

func BuildInsertQuery(td *Table, structValue reflect.Value, idPtr any, forceOnConflictExpr string, upsert bool, returningColumns ...string) (query string, args []any, err error) {
	colNames, colArgs, err := extractAllColumns(td, structValue)
	if err != nil {
		return
	}

	if len(colNames) == 0 {
		err = fmt.Errorf("no columns to insert for table %s", td.Name)
		return
	}

	var b strings.Builder
	fmt.Fprintf(&b, `INSERT INTO %s.%s`, Quote(td.SearchPath), Quote(td.Name))
	b.WriteString(" (")
	for i, name := range colNames {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(Quote(name))
	}
	b.WriteString(") VALUES (")
	for i := range colNames {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "$%d", i+1)
	}
	b.WriteString(")")

	if upsert && forceOnConflictExpr != "" {
		b.WriteString(" " + forceOnConflictExpr)
	}

	if len(returningColumns) > 0 {
		b.WriteString(" RETURNING ")
		if returningColumns[0] == "*" {
			b.WriteString("*")
		} else {
			for i, col := range returningColumns {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(Quote(col))
			}
		}
	} else if idPtr != nil {
		if primaryKey, ok := td.FindPrimaryKey(); ok {
			fmt.Fprintf(&b, ` RETURNING %s`, Quote(primaryKey.Name))
		}
	}

	b.WriteString(";")
	query = b.String()
	args = colArgs
	return
}

func BuildUpdateQuery(value any, columnsToUpdate []string, reportNotFound bool, primaryKey *Column, returningColumns ...string) (query string, args []any, err error) {
	val := IndirectValue(value)
	td := primaryKey.Table

	if reportNotFound {
		pkValue := val.FieldByIndex(primaryKey.FieldIndex).Interface()
		query = fmt.Sprintf(`SELECT 1 FROM %s.%s WHERE %s = $1;`,
			Quote(td.SearchPath), Quote(td.Name), Quote(primaryKey.Name))
		args = []any{pkValue}
		return
	}

	useSet := make(map[string]bool, len(columnsToUpdate))
	for _, name := range columnsToUpdate {
		useSet[name] = true
	}

	var setClauses []string
	argIdx := 1

	for _, col := range td.Columns {
		if col.AutoGenerated || col.Identity {
			continue
		}
		if col.PrimaryKey {
			continue
		}
		if !useSet[col.Name] {
			continue
		}

		field := val.FieldByIndex(col.FieldIndex)
		value := field.Interface()

		if col.Password && td.PasswordHandler != nil && td.PasswordHandler.canEncrypt() {
			strVal, ok := value.(string)
			if ok && strVal != "" {
				encrypted, encErr := td.PasswordHandler.Encrypt(td.Name, strVal)
				if encErr != nil {
					err = fmt.Errorf("encrypt password for column %s: %w", col.Name, encErr)
					return
				}
				value = encrypted
			}
		}

		setClauses = append(setClauses, fmt.Sprintf(`%s = $%d`, Quote(col.Name), argIdx))
		args = append(args, value)
		argIdx++
	}

	if len(setClauses) == 0 {
		err = fmt.Errorf("no columns to update for table %s", td.Name)
		return
	}

	pkValue := val.FieldByIndex(primaryKey.FieldIndex).Interface()
	args = append(args, pkValue)

	var b strings.Builder
	fmt.Fprintf(&b, `UPDATE %s.%s SET %s WHERE %s = $%d`,
		Quote(td.SearchPath), Quote(td.Name),
		strings.Join(setClauses, ", "),
		Quote(primaryKey.Name), argIdx)

	if len(returningColumns) > 0 {
		b.WriteString(" RETURNING ")
		if returningColumns[0] == "*" {
			b.WriteString("*")
		} else {
			for i, col := range returningColumns {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(Quote(col))
			}
		}
	}

	b.WriteString(";")
	query = b.String()
	return
}

func BuildDeleteQuery(td *Table, values []any) (query string, ids []any, err error) {
	primaryKey, ok := td.FindPrimaryKey()
	if !ok {
		err = fmt.Errorf("no primary key for table %s", td.Name)
		return
	}

	if len(values) == 0 {
		err = fmt.Errorf("no values to delete for table %s", td.Name)
		return
	}

	// Build a concretely-typed slice ([]T rather than []any) of primary-key
	// values. pgx v5 array encoding is driven by the Go element type: a []any
	// has no single element OID, so it fails for custom PK types (e.g. a
	// `type ID int64` or uuid.UUID). Constructing []T via reflection lets pgx
	// pick the correct array OID for the ANY($1) parameter.
	firstPK := IndirectValue(values[0]).FieldByIndex(primaryKey.FieldIndex)
	elemType := firstPK.Type()
	typedSlice := reflect.MakeSlice(reflect.SliceOf(elemType), 0, len(values))
	for _, v := range values {
		val := IndirectValue(v)
		typedSlice = reflect.Append(typedSlice, val.FieldByIndex(primaryKey.FieldIndex))
	}

	query = fmt.Sprintf(`DELETE FROM %s.%s WHERE %s = ANY($1);`,
		Quote(td.SearchPath), Quote(td.Name), Quote(primaryKey.Name))
	// The single $1 parameter is the whole typed slice.
	ids = []any{typedSlice.Interface()}
	return
}

func BuildExistsQuery(td *Table, structValue reflect.Value) (query string, args []any, err error) {
	var conditions []string
	argIdx := 1

	for _, col := range td.Columns {
		if col.Unscannable || col.Password {
			continue
		}

		field := structValue.FieldByIndex(col.FieldIndex)
		val := field.Interface()

		if isZero(val) {
			continue
		}

		conditions = append(conditions, fmt.Sprintf(`%s = $%d`, Quote(col.Name), argIdx))
		args = append(args, val)
		argIdx++
	}

	if len(conditions) == 0 {
		err = fmt.Errorf("no non-zero fields for exists query on table %s", td.Name)
		return
	}

	query = fmt.Sprintf(`SELECT EXISTS(SELECT 1 FROM %s.%s WHERE %s);`,
		Quote(td.SearchPath), Quote(td.Name),
		strings.Join(conditions, " AND "))
	return
}

func BuildDuplicateQuery(td *Table, newIDPtr any, returningColumns ...string) (query string, err error) {
	primaryKey, ok := td.FindPrimaryKey()
	if !ok {
		err = fmt.Errorf("no primary key for table %s", td.Name)
		return
	}

	var insertCols, selectCols []string
	for _, col := range td.Columns {
		if col.AutoGenerated || col.Identity {
			continue
		}
		insertCols = append(insertCols, Quote(col.Name))
		selectCols = append(selectCols, Quote(col.Name))
	}

	if len(insertCols) == 0 {
		err = fmt.Errorf("no columns to duplicate for table %s", td.Name)
		return
	}

	var b strings.Builder
	fmt.Fprintf(&b, `INSERT INTO %s.%s`, Quote(td.SearchPath), Quote(td.Name))
	b.WriteString(" (")
	b.WriteString(strings.Join(insertCols, ", "))
	b.WriteString(") SELECT ")
	b.WriteString(strings.Join(selectCols, ", "))
	fmt.Fprintf(&b, ` FROM %s.%s`, Quote(td.SearchPath), Quote(td.Name))
	fmt.Fprintf(&b, ` WHERE %s = $1`, Quote(primaryKey.Name))

	if len(returningColumns) > 0 {
		b.WriteString(" RETURNING ")
		if returningColumns[0] == "*" {
			b.WriteString("*")
		} else {
			for i, col := range returningColumns {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(Quote(col))
			}
		}
	} else if newIDPtr != nil {
		fmt.Fprintf(&b, ` RETURNING %s`, Quote(primaryKey.Name))
	}

	b.WriteString(";")
	query = b.String()
	return
}

func BuildCreateTableQuery(td *Table) string {
	var b strings.Builder
	fmt.Fprintf(&b, `CREATE TABLE %s.%s (`, Quote(td.SearchPath), Quote(td.Name))
	b.WriteString("\n")

	for i, col := range td.Columns {
		if i > 0 {
			b.WriteString(",\n")
		}
		fmt.Fprintf(&b, `    %s %s`, Quote(col.Name), col.Type.String())
		if col.TypeArgument != "" {
			fmt.Fprintf(&b, "(%s)", col.TypeArgument)
		}

		if col.AutoGenerated {
			if col.GeneratedExpression != "" {
				fmt.Fprintf(&b, " GENERATED ALWAYS AS (%s) STORED", col.GeneratedExpression)
			}
		} else if col.Identity {
			b.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
		} else {
			if !col.Nullable {
				b.WriteString(" NOT NULL")
			}
			if col.Default != "" {
				fmt.Fprintf(&b, " DEFAULT %s", col.Default)
			}
		}

		if col.PrimaryKey && !col.AutoGenerated && !col.Identity {
			b.WriteString(" PRIMARY KEY")
		}

		if col.Unique && !col.PrimaryKey {
			b.WriteString(" UNIQUE")
		}

		if col.CheckConstraint != "" {
			fmt.Fprintf(&b, " CHECK (%s)", col.CheckConstraint)
		}

		if col.Collate != "" {
			fmt.Fprintf(&b, " COLLATE %s", Quote(col.Collate))
		}
	}

	b.WriteString("\n);\n")
	return b.String()
}

func BuildAlterTableForeignKeysQueries(td *Table) []string {
	var queries []string

	for _, col := range td.Columns {
		if col.ReferenceTableName == "" {
			continue
		}

		constraintName := FKName(td.Name, []string{col.Name})

		var b strings.Builder
		fmt.Fprintf(&b, `ALTER TABLE %s.%s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s(%s)`,
			Quote(td.SearchPath), Quote(td.Name), Quote(constraintName),
			Quote(col.Name), Quote(col.ReferenceTableName), Quote(col.ReferenceColumnName))

		if col.ReferenceOnDelete != "" {
			b.WriteString(" ON DELETE " + col.ReferenceOnDelete)
		}
		if col.ReferenceOnUpdate != "" {
			b.WriteString(" ON UPDATE " + col.ReferenceOnUpdate)
		}
		if col.DeferrableReference {
			b.WriteString(" DEFERRABLE")
		}

		b.WriteString(";\n")
		queries = append(queries, b.String())
	}

	return queries
}

func ExtractPrimaryKeyValue(primaryKey *Column, val reflect.Value) (any, error) {
	field := val.FieldByIndex(primaryKey.FieldIndex)
	return field.Interface(), nil
}
