package schema

import (
	"fmt"
	"reflect"
	"strings"
)

// ColumnBuilder is the interface for building column definitions from database metadata.
type ColumnBuilder interface {
	BuildColumn(column *Column) error
}

// Column represents a database column definition with all metadata.
type Column struct {
	Table            *Table // back-reference to parent table
	TableName        string
	TableDescription string
	TableType        TableType

	Name         string
	Type         DataType
	TypeArgument string
	Description  string

	OrdinalPosition int
	FieldIndex      []int
	FieldType       reflect.Type
	FieldName       string

	PrimaryKey bool
	Identity   bool

	Default         string
	CheckConstraint string
	Unique          bool
	Conflict        string

	Username bool
	Password bool

	Nullable bool

	ReferenceTableName  string
	ReferenceColumnName string
	DeferrableReference bool
	ReferenceOnDelete   string
	ReferenceOnUpdate   string

	Index       IndexType
	UniqueIndex string

	Presenter           bool
	AutoGenerated       bool
	GeneratedExpression string

	Unscannable bool
	Collate     string

	TypeChangeUsing string

	SQLType   string
	Options   string
	IndexSort string
}

// IsGeneratedTimestamp returns true if this column is a generated timestamp.
func (c *Column) IsGeneratedTimestamp() bool {
	return c.AutoGenerated && c.Type.IsTime()
}

// IsGeneratedPrimaryUUID returns true if this column is a generated primary UUID.
func (c *Column) IsGeneratedPrimaryUUID() bool {
	return c.AutoGenerated && c.PrimaryKey && (c.Type == UUID || c.Type.String() == "uuid")
}

// IsGenerated returns true if this column is auto-generated.
func (c *Column) IsGenerated() bool {
	return c.AutoGenerated
}

// FieldTagString returns the db struct tag string for this column.
func (c *Column) FieldTagString(strict bool) string {
	var b strings.Builder
	b.WriteString("name=" + c.Name)
	if c.TypeArgument != "" {
		fmt.Fprintf(&b, ",type=%s(%s)", c.Type, c.TypeArgument)
	} else if c.Type != 0 {
		fmt.Fprintf(&b, ",type=%s", c.Type)
	}
	if c.PrimaryKey {
		b.WriteString(",pk")
	}
	if c.Identity {
		b.WriteString(",identity")
	}
	if c.Unique {
		b.WriteString(",unique")
	}
	if c.UniqueIndex != "" {
		fmt.Fprintf(&b, ",unique_index=%s", c.UniqueIndex)
	}
	if c.Index != InvalidIndex {
		fmt.Fprintf(&b, ",index=%s", c.Index)
	}
	if c.Default != "" {
		fmt.Fprintf(&b, ",default=%s", c.Default)
	}
	if c.CheckConstraint != "" {
		fmt.Fprintf(&b, ",check=%s", c.CheckConstraint)
	}
	if c.ReferenceTableName != "" {
		fmt.Fprintf(&b, ",ref=%s(%s", c.ReferenceTableName, c.ReferenceColumnName)
		if c.ReferenceOnDelete != "" {
			b.WriteString(" " + c.ReferenceOnDelete)
		}
		if c.ReferenceOnUpdate != "" {
			b.WriteString(" " + c.ReferenceOnUpdate)
		}
		b.WriteString(")")
	}
	if c.Username {
		b.WriteString(",username")
	}
	if c.Password {
		b.WriteString(",password")
	}
	if !c.Nullable && !c.PrimaryKey && !c.AutoGenerated {
		b.WriteString(",notnull")
	}
	if c.Presenter {
		b.WriteString(",presenter")
	}
	if c.AutoGenerated {
		fmt.Fprintf(&b, ",generated=%s", c.GeneratedExpression)
	}
	if strict && c.Unscannable {
		b.WriteString(",unscannable")
	}
	if c.Collate != "" {
		fmt.Fprintf(&b, ",collate=%s", c.Collate)
	}
	if c.TypeChangeUsing != "" {
		fmt.Fprintf(&b, ",using=%s", c.TypeChangeUsing)
	}
	return b.String()
}
