package schema

import (
	"fmt"
	"reflect"
)

func extractAllColumns(td *Table, val reflect.Value) (colNames []string, colArgs []any, err error) {
	return extractColumns(td, val, nil)
}

func extractColumns(td *Table, val reflect.Value, columnsToUse []string) (colNames []string, colArgs []any, err error) {
	var useSet map[string]bool
	if len(columnsToUse) > 0 {
		useSet = make(map[string]bool, len(columnsToUse))
		for _, name := range columnsToUse {
			useSet[name] = true
		}
	}

	for _, col := range td.Columns {
		if col.AutoGenerated || col.Identity {
			continue
		}
		if col.Unscannable {
			continue
		}
		if useSet != nil && !useSet[col.Name] {
			continue
		}

		field := val.FieldByIndex(col.FieldIndex)

		if col.PrimaryKey && field.IsZero() {
			// A zero-valued primary key is assumed to be DB-generated
			// (bigserial/serial default, sequence, etc.) and is left out
			// of the statement so the database assigns it. A non-zero PK
			// (e.g. an application-generated UUID) is included below like
			// any other column.
			continue
		}

		value := field.Interface()

		if col.Password && td.PasswordHandler != nil && td.PasswordHandler.canEncrypt() {
			strVal, ok := value.(string)
			if ok && strVal != "" {
				encrypted, encErr := td.PasswordHandler.Encrypt(td.Name, strVal)
				if encErr != nil {
					err = fmt.Errorf("encrypt password for column %s: %w", col.Name, encErr)
					return
				}
				value = encrypted
			}
		}

		colNames = append(colNames, col.Name)
		colArgs = append(colArgs, value)
	}

	return
}
