-- Mirage migration V20260718134512
-- Checksum: sha256:6ed5c322abd891009a42249ac6d1a91e67290178778d0a0a29b39be6ac40f3e3

-- +migrate Up

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA "public";

CREATE TYPE post_status AS ENUM ('draft', 'published', 'archived');

CREATE TYPE user_role AS ENUM ('guest', 'member', 'moderator', 'admin');

CREATE TABLE IF NOT EXISTS categories (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "parent_id" bigint,
    "name" varchar(255) NOT NULL,
    "slug" varchar(255) NOT NULL,
    "description" text,
    "sort_order" int DEFAULT 0,
    "is_active" bool DEFAULT true,
    "depth" int DEFAULT 0,
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    "updated_at" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "pk_categories" PRIMARY KEY ("id"),
    CONSTRAINT "uq_categories_slug" UNIQUE ("slug"),
    CONSTRAINT "fk_categories_parent_id" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") ON DELETE SET NULL
);

COMMENT ON TABLE categories IS 'Product category tree with self-referencing hierarchy';

CREATE TABLE IF NOT EXISTS products (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "category_id" bigint NOT NULL,
    "sku" varchar(100) NOT NULL,
    "name" varchar(500) NOT NULL,
    "slug" varchar(500) NOT NULL,
    "summary" text,
    "body" text,
    "price_cents" bigint NOT NULL,
    "currency_code" char(3) NOT NULL DEFAULT 'USD',
    "weight_grams" int,
    "width_mm" int,
    "height_mm" int,
    "depth_mm" int,
    "stock_quantity" int NOT NULL DEFAULT 0,
    "stock_status" varchar(20) NOT NULL DEFAULT 'in_stock',
    "is_published" bool DEFAULT false,
    "is_featured" bool DEFAULT false,
    "meta_title" varchar(255),
    "meta_description" text,
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    "updated_at" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "pk_products" PRIMARY KEY ("id"),
    CONSTRAINT "uq_products_sku" UNIQUE ("sku"),
    CONSTRAINT "uq_products_slug" UNIQUE ("slug"),
    CONSTRAINT "fk_products_category_id" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE RESTRICT,
    CONSTRAINT "chk_products_1" CHECK (price_cents >= 0),
    CONSTRAINT "chk_products_2" CHECK (weight_grams > 0),
    CONSTRAINT "chk_products_3" CHECK (stock_quantity >= 0),
    CONSTRAINT "chk_products_4" CHECK (stock_status IN ('in_stock','out_of_stock','preorder','discontinued'))
);

COMMENT ON TABLE products IS 'Product catalog with pricing and inventory';

CREATE TABLE IF NOT EXISTS product_images (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "product_id" bigint NOT NULL,
    "url" varchar(1024) NOT NULL,
    "alt_text" varchar(255),
    "sort_order" int DEFAULT 0,
    "is_primary" bool DEFAULT false,
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "pk_product_images" PRIMARY KEY ("id"),
    CONSTRAINT "fk_product_images_product_id" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE
);

COMMENT ON TABLE product_images IS 'Product image gallery with ordering';

CREATE TABLE IF NOT EXISTS product_variants (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "product_id" bigint NOT NULL,
    "sku" varchar(100) NOT NULL,
    "name" varchar(255) NOT NULL,
    "price_cents" bigint NOT NULL,
    "stock_quantity" int NOT NULL DEFAULT 0,
    "attributes_json" jsonb,
    "is_available" bool DEFAULT true,
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    "updated_at" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "pk_product_variants" PRIMARY KEY ("id"),
    CONSTRAINT "uq_product_variants_sku" UNIQUE ("sku"),
    CONSTRAINT "fk_product_variants_product_id" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE,
    CONSTRAINT "chk_product_variants_1" CHECK (price_cents >= 0),
    CONSTRAINT "chk_product_variants_2" CHECK (stock_quantity >= 0)
);

COMMENT ON TABLE product_variants IS 'Product variants for size/color/etc';

CREATE TABLE IF NOT EXISTS tags (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "slug" varchar(100) NOT NULL,
    "color" varchar(7),
    "post_count" int DEFAULT 0,
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "pk_tags" PRIMARY KEY ("id"),
    CONSTRAINT "uq_tags_name" UNIQUE ("name"),
    CONSTRAINT "uq_tags_slug" UNIQUE ("slug")
);

COMMENT ON TABLE tags IS 'Content tags for categorization';

CREATE TABLE IF NOT EXISTS users (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "username" varchar(100) NOT NULL,
    "email" varchar(255) NOT NULL,
    "password" varchar(255) NOT NULL,
    "role" user_role NOT NULL DEFAULT 'member',
    "status" varchar(20) NOT NULL DEFAULT 'active',
    "first_name" varchar(100),
    "last_name" varchar(100),
    "bio" text,
    "avatar_url" varchar(512),
    "login_count" int DEFAULT 0,
    "last_login_at" timestamptz,
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    "updated_at" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "pk_users" PRIMARY KEY ("id"),
    CONSTRAINT "uq_users_email" UNIQUE ("email"),
    CONSTRAINT "chk_users_1" CHECK (status IN ('active','suspended','deleted'))
);

COMMENT ON TABLE users IS 'User accounts with authentication and profile data';

CREATE TABLE IF NOT EXISTS events (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "session_id" varchar(255) NOT NULL,
    "event_type" varchar(100) NOT NULL,
    "resource_type" varchar(50),
    "resource_id" bigint,
    "path" varchar(1024) NOT NULL,
    "referrer" varchar(1024),
    "user_agent" text,
    "ip_address" inet,
    "metadata_json" jsonb,
    "duration_ms" int,
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "pk_events" PRIMARY KEY ("id", "created_at"),
    CONSTRAINT "fk_events_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL
) PARTITION BY RANGE ("created_at");

COMMENT ON TABLE events IS 'User activity events for analytics';

CREATE TABLE IF NOT EXISTS posts (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "title" varchar(500) NOT NULL,
    "slug" varchar(500) NOT NULL,
    "excerpt" text,
    "body" text NOT NULL,
    "status" post_status NOT NULL DEFAULT 'draft',
    "published_at" timestamptz,
    "view_count" int DEFAULT 0,
    "is_pinned" bool DEFAULT false,
    "is_locked" bool DEFAULT false,
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    "updated_at" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "pk_posts" PRIMARY KEY ("id"),
    CONSTRAINT "uq_posts_slug" UNIQUE ("slug"),
    CONSTRAINT "fk_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

COMMENT ON TABLE posts IS 'Blog posts with content and metadata';

CREATE TABLE IF NOT EXISTS comments (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "post_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "parent_id" bigint,
    "body" text NOT NULL,
    "is_approved" bool DEFAULT false,
    "is_spam" bool DEFAULT false,
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    "updated_at" timestamptz NOT NULL DEFAULT NOW(),
    "deleted_at" timestamptz,
    CONSTRAINT "pk_comments" PRIMARY KEY ("id"),
    CONSTRAINT "fk_comments_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_comments_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_comments_parent_id" FOREIGN KEY ("parent_id") REFERENCES "comments" ("id") ON DELETE CASCADE
);

COMMENT ON TABLE comments IS 'Threaded comments on posts';

CREATE TABLE IF NOT EXISTS post_tags (
    "post_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL,
    "sort_order" int DEFAULT 0,
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT "fk_post_tags_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_post_tags_tag_id" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE
);

COMMENT ON TABLE post_tags IS 'Many-to-many relationship between posts and tags';

CREATE OR REPLACE FUNCTION "update_timestamps"()
    RETURNS trigger
    LANGUAGE plpgsql
    IMMUTABLE
    SECURITY DEFINER
AS $func_a04657bb$
BEGIN
	NEW.updated_at = now();
	RETURN NEW;
END;
$func_a04657bb$;

COMMENT ON FUNCTION "update_timestamps" IS 'Sets updated_at to current timestamp on INSERT or UPDATE';

CREATE TRIGGER "trg_users_updated_at"
    BEFORE INSERT OR UPDATE ON "users"
    FOR EACH ROW
    EXECUTE FUNCTION "update_timestamps"();

COMMENT ON TRIGGER "trg_users_updated_at" ON "users" IS 'Auto-update updated_at column on users';

CREATE OR REPLACE VIEW "active_users" AS
SELECT id, username, email, role, created_at FROM users WHERE status = 'active';

COMMENT ON VIEW "active_users" IS 'Users that are not suspended or deleted';

GRANT SELECT, INSERT, UPDATE ON TABLE "users" TO "app_role";

CREATE POLICY "user_isolation" ON "users"
    AS PERMISSIVE
    FOR ALL
    TO "app_role"
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

-- +migrate Down

DROP POLICY IF EXISTS "user_isolation" ON "users";

REVOKE SELECT, INSERT, UPDATE ON TABLE "users" FROM "app_role";

DROP TRIGGER IF EXISTS "trg_users_updated_at" ON "users";

DROP VIEW IF EXISTS "active_users";

DROP FUNCTION IF EXISTS "update_timestamps"();

DROP EXTENSION IF EXISTS "uuid-ossp";

DROP TABLE IF EXISTS post_tags;

DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS posts;

DROP TABLE IF EXISTS events;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS tags;

DROP TABLE IF EXISTS product_variants;

DROP TABLE IF EXISTS product_images;

DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS categories;

DROP TYPE IF EXISTS user_role;

DROP TYPE IF EXISTS post_status;

