-- Migration: V20260830170843_evolve_v6
-- Generated by mirage at 2026-08-30T17:08:43Z
-- Checksum: sha256:739c28f4f4f95f962c4d55f4dec60ac436b990b5df2c238e6063d92f6e163b50
-- Message: evolve v6

-- +migrate Up

CREATE TABLE IF NOT EXISTS plain_favorites (
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    "updated_at" timestamptz NOT NULL DEFAULT NOW(),
    "id" bigint NOT NULL,
    "target_type" varchar(50) NOT NULL,
    "target_id" bigint NOT NULL,
    CONSTRAINT "uq_plain_favorites_target_type_target_id" UNIQUE ("target_type", "target_id")
);

COMMENT ON TABLE plain_favorites IS 'Generic favorites with composite unique and index on target';

ALTER TABLE users ADD COLUMN "bio" text;

ALTER TABLE users RENAME COLUMN "avatar_uri" TO "avatar_url";

ALTER TABLE users ALTER COLUMN "last_name" TYPE varchar(100) USING "last_name"::varchar(100);

ALTER TABLE users ALTER COLUMN "login_count" SET DEFAULT 0;

CREATE INDEX "idx_plain_favorites_target_type_target_id" ON plain_favorites ("target_type" ASC, "target_id" ASC);

CREATE OR REPLACE VIEW "active_users" AS
SELECT id, username, email, role, created_at FROM users WHERE status = 'active';

COMMENT ON VIEW "active_users" IS 'Users that are not suspended or deleted';

-- +migrate Down

CREATE OR REPLACE VIEW "active_users" AS
SELECT id, username, email, role, created_at FROM users WHERE status = 'active' AND role='member';

COMMENT ON VIEW "active_users" IS 'Users that are not suspended or deleted (v5: members only)';

ALTER TABLE users RENAME COLUMN "avatar_url" TO "avatar_uri";

ALTER TABLE users ALTER COLUMN "login_count" SET DEFAULT 1;

ALTER TABLE users ALTER COLUMN "last_name" TYPE varchar(200) USING "last_name"::varchar(200);

ALTER TABLE users DROP COLUMN "bio";

DROP INDEX IF EXISTS "idx_plain_favorites_target_type_target_id";

DROP TABLE IF EXISTS plain_favorites;

