-- Migration: V20260830170819_evolve_v2
-- Generated by mirage at 2026-08-30T17:08:19Z
-- Checksum: sha256:497465563a6be5d5e4114d0c63ad91223893ad5be442f47f9d64fe7587183ad6
-- Message: evolve v2

-- +migrate Up

ALTER TABLE users ADD COLUMN "extra" jsonb;

ALTER TABLE users ADD COLUMN "preferences" jsonb;

ALTER TABLE users ADD COLUMN "settings" jsonb NOT NULL DEFAULT '{}';

ALTER TABLE users ALTER COLUMN "role" SET DEFAULT 'member';

-- +migrate Down

ALTER TABLE users DROP COLUMN "settings";

ALTER TABLE users ALTER COLUMN "role" SET DEFAULT 'guest';

ALTER TABLE users DROP COLUMN "preferences";

ALTER TABLE users DROP COLUMN "extra";

