-- Migration: V20260830170829_evolve_v3
-- Generated by mirage at 2026-08-30T17:08:29Z
-- Checksum: sha256:b4c2c615083d55d517d19851742b054a71af71d011babc4ebb52497c015df736
-- Message: evolve v3

-- +migrate Up

ALTER TABLE users RENAME COLUMN "avatar_url" TO "avatar_uri";

ALTER TABLE users ALTER COLUMN "last_name" TYPE varchar(200) USING "last_name"::varchar(200);

ALTER TABLE users ALTER COLUMN "login_count" SET DEFAULT 1;

-- +migrate Down

ALTER TABLE users RENAME COLUMN "avatar_uri" TO "avatar_url";

ALTER TABLE users ALTER COLUMN "login_count" SET DEFAULT 0;

ALTER TABLE users ALTER COLUMN "last_name" TYPE varchar(100) USING "last_name"::varchar(100);

