-- Migration: V20260830170833_evolve_v4
-- Generated by mirage at 2026-08-30T17:08:33Z
-- Checksum: sha256:5d230abd7846ea628eb6c15002d7a5aa143fcf6ab8900a01ef63659c95abea5a
-- Message: evolve v4

-- +migrate Up

CREATE TABLE events_2024_q1 PARTITION OF "events" FOR VALUES FROM ('2024-01-01') TO ('2024-04-01');

-- +migrate Down

DROP TABLE IF EXISTS events_2024_q1;

