-- Migration: V20260830170838_evolve_v5
-- Generated by mirage at 2026-08-30T17:08:38Z
-- Checksum: sha256:1ac3d3a33eef30e61a68aea7eb1dd3a423ae4f9ab346fbb5dcbba08ab277e09f
-- Message: evolve v5
--
-- WARNING: destructive changes in this migration:
--

-- +migrate Up

CREATE OR REPLACE VIEW "active_users" AS
SELECT id, username, email, role, created_at FROM users WHERE status = 'active' AND role='member';

COMMENT ON VIEW "active_users" IS 'Users that are not suspended or deleted (v5: members only)';

ALTER TABLE users DROP COLUMN "bio";

DROP TABLE IF EXISTS plain_favorites;

-- +migrate Down

CREATE OR REPLACE VIEW "active_users" AS
SELECT id, username, email, role, created_at FROM users WHERE status = 'active';

COMMENT ON VIEW "active_users" IS 'Users that are not suspended or deleted';

CREATE TABLE IF NOT EXISTS plain_favorites (
    "created_at" timestamptz NOT NULL DEFAULT NOW(),
    "updated_at" timestamptz NOT NULL DEFAULT NOW(),
    "id" bigint NOT NULL,
    "target_type" varchar(50) NOT NULL,
    "target_id" bigint NOT NULL,
    CONSTRAINT "uq_plain_favorites_target_type_target_id" UNIQUE ("target_type", "target_id")
);

COMMENT ON TABLE plain_favorites IS 'Generic favorites with composite unique and index on target';

ALTER TABLE users ADD COLUMN "bio" text;

